name: Jest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
    - name: Run Jest
      run: npm run test
    - name: Deploy Infrastructure
      if: steps.jest.outcome == 'success'
      run: scripts/deploy.sh